### ISSUE TITLE
minimize cluster-deployer clusterrole

### ISSUE THREAD

**Issue by themightychris** [JarvusInnovations/cluster-template#2]
Some projects are using a clusterrole provided in the jarvus library to create auth for github actions to `kubectl diff` and `kubectl apply` the whole cluster. The current example uses total `*` wildcards, perhaps the verbs could be restricted and still support deployment?

Also, should the manifests for such a role be baked into the cluster-template?

**Comment by themightychris** [comment]
I tried to use this service account and it didn't seem to have access to anything, back to using the vendor-provided admin kubeconfig:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-deployer
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-deployer
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-deployer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-deployer
subjects:
- kind: ServiceAccount
  name: cluster-deployer
  namespace: kube-system
```
